version: '3.1'

services:

  app:
    container_name: feedback_app
    build: app
    depends_on:
      - db
    restart: "no"
    env_file: app/.env
    ports:
      - 3838:3838
    volumes:
      - /Users/tim/Library/Application Support/renv/cache:/renv/cache
      - ./app/src:/dev/src

  db:
    container_name: feedback_db
    build: db
    restart: always
    env_file: db/.env
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql

  adminer:
    container_name: feedback_panel
    image: adminer
    restart: always
    ports:
      - 8080:8080
